version: '3.9'
services:
  db:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '9150:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATA_CRMBASE=crm
      - TZ=Asia/Bangkok
    volumes:
      - ./mysql_data_crm:/var/lib/mysql
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data_crm:/data
    command: redis-server --appendonly yes

volumes:
  mysql_data_crm:
  redis_data_crm:
